import type { Metadata } from "next";
import "./paypal.css"



export const metadata: Metadata = {
  title: "Paypal - Homepage Recreation",
  description: "Generated by create next app",
  icons: {
    icon: "/paypal/icons/paypalLogo.png",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full h-screen font-PaypalSans">

        {children}

    </section>
  );
}
