import type { Metadata } from "next";
import NavBar from "./apple/components/NavBar";
import Footer from "./apple/components/Footer";
import "./apple/css/Apple.css";
import MobileNavBar from "./apple/components/MobileNavBar";

export const metadata: Metadata = {
  title: "Apple - Homepage Recreation",
  description: "Generated by create next app",
  icons: {
    icon: "/apple/img/appleFavicon.png",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full flex flex-col items-center h-screen font-helvetica overflow-y-auto">

      <NavBar />

      <MobileNavBar />

      <div className="w-full max-w-[2560px]">
        {children}
      </div>
      <Footer />
    </section>
  );
}
