export const NavBarItems: NavBarItem[] = [
    {
        name: "Store",
        firstTabTittle: "Shop",
        firstTabItems: [
            { name: "Shop the latest", path: "/store/" },
            { name: "Mac", path: "/store/buy-mac/" },
            { name: "iPad", path: "/store/buy-ipad/" },
            { name: "iPhone", path: "/store/buy-iphone/" },
            { name: "Apple Watch", path: "/store/buy-apple-watch/" },
            { name: "Apple Vision Pro", path: "/store/buy-apple-vision-pro/" },
            { name: "Accessories", path: "/store/accessories/" },
        ],
        secondTabTittle: "Quick Links",
        secondTabItems: [
            { name: "Shop Holiday Gifts", path: "/store/" },
            { name: "Find a store", path: "/retail/" },
            { name: "Order Status", path: "/account/" },
            { name: "Apple Trade In", path: "/shop/trade-in/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "Shop Special Stores",
        thirdTabItems: [
            { name: "Certified Refurbished", path: "/us-edu/shop/refurbished/" },
            { name: "Education", path: "/us-edu/store/" },
            { name: "Business", path: "/retail/business/" },
            { name: "Veterans and Military", path: "/shop/browse/home/veterans_military/" },
            { name: "Government", path: "/r/store/government/" },
        ],
    },
    {
        name: "Mac",
        firstTabTittle: "Explore Mac",
        firstTabItems: [
            { name: "Explore All Mac", path: "/mac/explore-all-mac/" },
            { name: "MacBook Air", path: "/mac/macbook-air/" },
            { name: "MacBook Pro", path: "/mac/macbook-pro/" },
            { name: "iMac", path: "/mac/imac/" },
            { name: "Mac mini", path: "/mac/mac-mini/" },
            { name: "Mac Studio", path: "/mac/mac-studio/" },
            { name: "Mac Pro", path: "/mac/mac-pro/" },
            { name: "Displays", path: "/mac/displays/" },
        ],
        secondTabTittle: "Shop Mac",
        secondTabItems: [
            { name: "Shop Mac", path: "/shop/mac/" },
            { name: "Help Me Choose", path: "/shop/mac/help-me-choose/" },
            { name: "Mac Accessories", path: "/shop/mac/accessories/" },
            { name: "Apple Trade In", path: "/shop/trade-in/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "More from Mac",
        thirdTabItems: [
            { name: "Mac Support", path: "/mac/support/" },
            { name: "AppleCare+ for Mac", path: "/mac/applecare/" },
            { name: "macOS Sequoia", path: "/mac/macos-sequoia/" },
            { name: "Apple Intelligence", path: "/mac/intelligence/" },
            { name: "Apps by Apple", path: "/mac/apps/" },
            { name: "Continuity", path: "/mac/continuity/" },
            { name: "iCloud+", path: "/mac/icloud/" },
            { name: "Mac for Business", path: "/mac/business/" },
            { name: "Education", path: "/mac/education/" },
        ],
        fourthTabItems: [
            { name: "Compare Mac", path: "/mac/compare/" },
            { name: "Switch from PC to Mac", path: "/mac/switch/" },
        ],
    },
    {
        name: "iPad",
        firstTabTittle: "Explore iPad",
        firstTabItems: [
            { name: "Explore All iPad", path: "/ipad/explore-all-ipad/" },
            { name: "iPad Pro", path: "/ipad/ipad-pro/" },
            { name: "iPad Air", path: "/ipad/ipad-air/" },
            { name: "iPad", path: "/ipad/ipad/" },
            { name: "iPad mini", path: "/ipad/ipad-mini/" },
            { name: "Apple Pencil", path: "/ipad/apple-pencil/" },
            { name: "Keyboards", path: "/ipad/keyboards/" },
        ],
        secondTabTittle: "Shop iPad",
        secondTabItems: [
            { name: "Shop iPad", path: "/shop/ipad/" },
            { name: "iPad Accessories", path: "/shop/ipad/accessories/" },
            { name: "Apple Trade In", path: "/shop/trade-in/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "More from iPad",
        thirdTabItems: [
            { name: "iPad Support", path: "/ipad/support/" },
            { name: "AppleCare+ for iPad", path: "/ipad/applecare/" },
            { name: "iPadOS 18", path: "/ipad/ipados-18/" },
            { name: "Apple Intelligence", path: "/ipad/intelligence/" },
            { name: "Apps by Apple", path: "/ipad/apps/" },
            { name: "iCloud+", path: "/ipad/icloud/" },
            { name: "Education", path: "/ipad/education/" },
        ],
        fourthTabItems: [
            { name: "Compare iPad", path: "/ipad/compare/" },
            { name: "Why iPad", path: "/ipad/why-ipad/" },
        ],
    },
    {
        name: "iPhone",
        firstTabTittle: "Explore iPhone",
        firstTabItems: [
            { name: "Explore All iPhone", path: "/iphone/explore-all-iphone/" },
            { name: "iPhone 16 Pro", path: "/iphone/iphone-16-pro/" },
            { name: "iPhone 16", path: "/iphone/iphone-16/" },
            { name: "iPhone 15", path: "/iphone/iphone-15/" },
            { name: "iPhone 14", path: "/iphone/iphone-14/" },
            { name: "iPhone SE", path: "/iphone/iphone-se/" },
        ],
        secondTabTittle: "Shop iPhone",
        secondTabItems: [
            { name: "Shop iPhone", path: "/shop/iphone/" },
            { name: "iPhone Accessories", path: "/shop/iphone/accessories/" },
            { name: "Apple Trade In", path: "/shop/trade-in/" },
            { name: "Carrier Deals at Apple", path: "/shop/iphone/carrier-deals/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "More from iPhone",
        thirdTabItems: [
            { name: "iPhone Support", path: "/iphone/support/" },
            { name: "AppleCare+ for iPhone", path: "/iphone/applecare/" },
            { name: "iOS 18", path: "/iphone/ios-18/" },
            { name: "Apple Intelligence", path: "/iphone/intelligence/" },
            { name: "Apps by Apple", path: "/iphone/apps/" },
            { name: "iPhone Privacy", path: "/iphone/privacy/" },
            { name: "iCloud+", path: "/iphone/icloud/" },
            { name: "Wallet, Pay, Card", path: "/iphone/wallet-pay-card/" },
            { name: "Siri", path: "/iphone/siri/" },
        ],
        fourthTabItems: [
            { name: "Compare iPhone", path: "/iphone/compare/" },
            { name: "Switch from Android", path: "/iphone/switch-from-android/" },
        ],
    },
    {
        name: "Watch",
        firstTabTittle: "Explore Watch",
        firstTabItems: [
            { name: "Explore All Apple Watch", path: "/watch/explore-all-apple-watch/" },
            { name: "Apple Watch Series 10", path: "/watch/apple-watch-series-10/" },
            { name: "Apple Watch Ultra 2", path: "/watch/apple-watch-ultra-2/" },
            { name: "Apple Watch SE", path: "/watch/apple-watch-se/" },
            { name: "Apple Watch Nike", path: "/watch/apple-watch-nike/" },
            { name: "Apple Watch Hermès", path: "/watch/apple-watch-hermes/" },
        ],
        secondTabTittle: "Shop Watch",
        secondTabItems: [
            { name: "Shop Apple Watch", path: "/shop/watch/" },
            { name: "Apple Watch Studio", path: "/shop/watch/studio/" },
            { name: "Apple Watch Bands", path: "/shop/watch/bands/" },
            { name: "Apple Watch Accessories", path: "/shop/watch/accessories/" },
            { name: "Apple Trade In", path: "/shop/trade-in/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "More from Watch",
        thirdTabItems: [
            { name: "Apple Watch Support", path: "/watch/support/" },
            { name: "AppleCare+ for Watch", path: "/watch/applecare/" },
            { name: "watchOS 11", path: "/watch/watchos-11/" },
            { name: "Apple Watch For Your Kids", path: "/watch/for-your-kids/" },
            { name: "Apps by Apple", path: "/watch/apps/" },
            { name: "Apple Fitness+", path: "/watch/fitness-plus/" },
        ],
        fourthTabItems: [
            { name: "Compare Watch", path: "/watch/compare/" },
            { name: "Why Apple Watch", path: "/watch/why-apple-watch/" },
        ],
    },
    {
        name: "Vision",
        firstTabTittle: "Explore Vision",
        firstTabItems: [
            { name: "Explore Apple Vision Pro", path: "/vision/explore-apple-vision-pro/" },
            { name: "Guided Tour", path: "/vision/guided-tour/" },
            { name: "Tech Specs", path: "/vision/tech-specs/" },
        ],
        secondTabTittle: "Shop Vision",
        secondTabItems: [
            { name: "Shop Apple Vision Pro", path: "/shop/vision-pro/" },
            { name: "Apple Vision Pro Accessories", path: "/shop/vision-pro/accessories/" },
            { name: "Book a Demo", path: "/shop/vision-pro/book-a-demo/" },
            { name: "Financing", path: "/shop/browse/financing/" },
        ],
        thirdTabTittle: "More from Vision",
        thirdTabItems: [
            { name: "Apple Vision Pro Support", path: "/vision/support/" },
            { name: "AppleCare+", path: "/vision/applecare/" },
            { name: "visionOS 2", path: "/vision/visionos-2/" },
        ],
    },
    {
        name: "AirPods",
        firstTabTittle: "Explore AirPods",
        firstTabItems: [
            { name: "Explore All AirPods", path: "/airpods/explore-all-airpods/" },
            { name: "AirPods 4", path: "/airpods/airpods-4/" },
            { name: "AirPods Pro 2", path: "/airpods/airpods-pro-2/" },
            { name: "AirPods Max", path: "/airpods/airpods-max/" },
            { name: "Compare AirPods", path: "/airpods/compare/" },
        ],
        secondTabTittle: "Shop AirPods",
        secondTabItems: [
            { name: "Shop AirPods", path: "/shop/airpods/" },
            { name: "AirPods Accessories", path: "/shop/airpods/accessories/" },
        ],
        thirdTabTittle: "More from AirPods",
        thirdTabItems: [
            { name: "AirPods Support", path: "/airpods/support/" },
            { name: "AppleCare+ for Headphones", path: "/airpods/applecare/" },
            { name: "Hearing Health", path: "/airpods/hearing-health/" },
            { name: "Apple Music", path: "/apple-music/" },
        ],
    },
    {
        name: "TV & Home",
        firstTabTittle: "Explore TV & Home",
        firstTabItems: [
            { name: "Explore TV & Home", path: "/tv-home/explore/" },
            { name: "Apple TV 4K", path: "/tv-home/apple-tv-4k/" },
            { name: "HomePod", path: "/tv-home/homepod/" },
            { name: "HomePod mini", path: "/tv-home/homepod-mini/" },
        ],
        secondTabTittle: "Shop TV & Home",
        secondTabItems: [
            { name: "Shop Apple TV 4K", path: "/shop/tv-home/apple-tv-4k/" },
            { name: "Shop HomePod", path: "/shop/tv-home/homepod/" },
            { name: "Shop HomePod mini", path: "/shop/tv-home/homepod-mini/" },
            { name: "Shop Siri Remote", path: "/shop/tv-home/siri-remote/" },
            { name: "TV & Home Accessories", path: "/shop/tv-home/accessories/" },
        ],
        thirdTabTittle: "More from TV & Home",
        thirdTabItems: [
            { name: "Apple TV Support", path: "/tv-home/support/apple-tv/" },
            { name: "HomePod Support", path: "/tv-home/support/homepod/" },
            { name: "AppleCare+", path: "/tv-home/applecare/" },
            { name: "Apple TV app", path: "/tv-home/apple-tv-app/" },
            { name: "Apple TV+", path: "/tv-home/apple-tv-plus/" },
            { name: "Home app", path: "/tv-home/home-app/" },
            { name: "Apple Music", path: "/tv-home/apple-music/" },
            { name: "Siri", path: "/tv-home/siri/" },
            { name: "AirPlay", path: "/tv-home/airplay/" },
        ],
    },
    {
        name: "Entertainment",
        firstTabTittle: "Explore Entertainment",
        firstTabItems: [
            { name: "Apple One", path: "/entertainment/apple-one/" },
            { name: "Apple TV+", path: "/entertainment/apple-tv-plus/" },
            { name: "Apple Music", path: "/entertainment/apple-music/" },
            { name: "Apple Arcade", path: "/entertainment/apple-arcade/" },
            { name: "Apple Fitness+", path: "/entertainment/apple-fitness-plus/" },
            { name: "Apple News+", path: "/entertainment/apple-news-plus/" },
            { name: "Apple Podcasts", path: "/entertainment/apple-podcasts/" },
            { name: "Apple Books", path: "/entertainment/apple-books/" },
            { name: "App Store", path: "/entertainment/app-store/" },
        ],
        secondTabTittle: "Support",
        secondTabItems: [
            { name: "Apple TV+ Support", path: "/entertainment/support/apple-tv-plus/" },
            { name: "Apple Music Support", path: "/entertainment/support/apple-music/" },
        ],
    },
    {
        name: "Accessories",
        firstTabTittle: "Shop Accessories",
        firstTabItems: [
            { name: "Shop All Accessories", path: "/accessories/shop-all/" },
            { name: "Mac", path: "/accessories/mac/" },
            { name: "iPad", path: "/accessories/ipad/" },
            { name: "iPhone", path: "/accessories/iphone/" },
            { name: "Apple Watch", path: "/accessories/apple-watch/" },
            { name: "Apple Vision Pro", path: "/accessories/apple-vision-pro/" },
            { name: "AirPods", path: "/accessories/airpods/" },
            { name: "TV & Home", path: "/accessories/tv-home/" },
        ],
        secondTabTittle: "Explore Accessories",
        secondTabItems: [
            { name: "Made by Apple", path: "/accessories/made-by-apple/" },
            { name: "Beats by Dr. Dre", path: "/accessories/beats/" },
            { name: "AirTag", path: "/accessories/airtag/" },
        ],
    },
    {
        name: "Support",
        firstTabTittle: "Explore Support",
        firstTabItems: [
            { name: "iPhone", path: "/support/iphone/" },
            { name: "Mac", path: "/support/mac/" },
            { name: "iPad", path: "/support/ipad/" },
            { name: "Watch", path: "/support/watch/" },
            { name: "Apple Vision Pro", path: "/support/vision-pro/" },
            { name: "AirPods", path: "/support/airpods/" },
            { name: "Music", path: "/support/music/" },
            { name: "TV", path: "/support/tv/" },
        ],
        secondTabTittle: "Get Help",
        secondTabItems: [
            { name: "Community", path: "/support/community/" },
            { name: "Check Coverage", path: "/support/check-coverage/" },
            { name: "Repair", path: "/support/repair/" },
        ],
        thirdTabTittle: "Helpful Topics",
        thirdTabItems: [
            { name: "Get AppleCare+", path: "/support/applecare/" },
            { name: "Apple Account and Password", path: "/support/account-password/" },
            { name: "Billing & Subscriptions", path: "/support/billing-subscriptions/" },
            { name: "Accessibility", path: "/support/accessibility/" },
        ],
    },
]