import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "5 different homepages",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {children}
    </section>
  );
}
