import type { Metadata } from "next";
import NavBar from "./spotify/components/NavBar";
import SideBar from "./spotify/components/SideBar";
import Footer from "./spotify/components/Footer";

export const metadata: Metadata = {
  title: "Spotify - Homepage Recreation",
  description: "Generated by create next app",
  icons: {
    icon: "/spotify/icons/spotifyFavicon.png",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full h-screen flex flex-col font-Gotham bg-black px-[8px] py-[8px]">
      <NavBar />

      <div className="w-full flex grow h-full min-h-[440px] overflow-y-hidden">
        <SideBar />
        {children}
      </div>

      <Footer />
    </section>
  );
}
